### ISSUE TITLE
Doesn`t work

### ISSUE THREAD

**Issue by Jhollman** [mikaeljorhult/brackets-todo#142] opened 2017-06-30 15:13 UTC
Does not work on the latets Brackets 1.9 version.
Not a single TODO comment, not inj JS, PHP or HMTL files.

**Comment by Jhollman** [comment] 2017-06-30 16:31
The problem seems to be with the "Comment Sintax" Regular Expresion.
I had to tweak till i managed it to work:

Prefix:   (?://* *@*)(
Sufix:   ):? *(.*?) ?(?=\*/|\r\n|\n|$)

This works for both JS and PHP files

**Comment by alelipona** [comment] 2017-07-09 00:36
What's file need to tweak?

**Comment by Jhollman** [comment] 2017-07-09 01:36
> What's file need to tweak?

Open the Plugin settings, a windows should pop, set the Prefix and Sufix fields as mentioned above.

**Comment by alelipona** [comment] 2017-07-11 07:57
A window dosen't pop :(

**Comment by Jhollman** [comment] 2017-07-11 18:13
Press CTRL + ALT + T   to open the TODO window.
Press the Configuration Gear Button on the right.
set the Prefix and Sufix fields as mentioned above.
Check the attached image.
![sin titulo](https://user-images.githubusercontent.com/10116951/28083370-75ef2882-664b-11e7-808a-1cd0dd423b58.jpg)

**Comment by alelipona** [comment] 2017-07-12 00:49
I have been pressing CTRL+ALT+T and TODO button to open the TODO window but a window is not opening. :-(

**Comment by Jhollman** [comment] 2017-07-12 01:00
do you have the latest version of both brackets and TODO?
Try Re-installing the TODO plugin.

**Comment by alelipona** [comment] 2017-07-12 01:56
> do you have the latest version of both brackets and TODO?
Yes
![screen shot 2017-07-12 at 07 45 11](https://user-images.githubusercontent.com/3032497/28098288-409fa792-66d7-11e7-97b0-df3e5709d7ba.png)
![screen shot 2017-07-12 at 07 52 17](https://user-images.githubusercontent.com/3032497/28098291-47a2ea7c-66d7-11e7-9d8d-17ef9e38b135.png)

> Try Re-installing the TODO plugin
I have try it but the  TODO window is not opening.
![screen shot 2017-07-12 at 07 51 20](https://user-images.githubusercontent.com/3032497/28098351-9eb0eea4-66d7-11e7-8cbe-0690f7e30ebb.png)

**Comment by Jhollman** [comment] 2017-07-12 17:34
Sorry, if nothing of before fixed the problem, i'm out of ideas.

**Comment by alvint** [comment] 2017-07-13 15:32
Commit 018a020 is the culprit. The issue is that the backslashes are not escaped in `modules/components/Defaults.js` line 10. The line:

    suffix: '):? *(.*?) ?(?=\/\*|-->|\*\/|\r\n|\n|\r|$)'

should be:

    suffix: '):? *(.*?) ?(?=\\/\\*|-->|\\*\\/|\\r\\n|\\n|\\r|$)'

You should be able to edit your copy of this file (on macOS it's at `/Users/yourname/Library/Application Support/Brackets/extensions/user/mikaeljolt.brackets-todo/modules/components/Defaults.js`, remove any current settings in your config, and restarting.

Can someone make a pull request?

**Comment by Jhollman** [comment] 2017-07-13 16:04
Works!, and under Windows the file is located in:   `%AppData%\Brackets\extensions\user\mikaeljorhult.brackets-todo\modules`
.

**Comment by nextgensparx** [comment] 2017-08-09 10:12
@alvint I created a [pull request](https://github.com/mikaeljorhult/brackets-todo/pull/144)

**Comment by therealcode** [comment] 2017-08-30 20:00
This worked wonder for me! The TODO Window never opened up. 

On Windows, I did the change @alvint suggested but referencing @Jhollman for location in Windows. Good work guys!

***Currently Using:*** 
Windows 10 64bit - i5
Brackets (Release 1.10 build 1.10.0-17483)

**Comment by mikaeljorhult** [comment] 2017-09-06 17:58
A fix for this is in the just released version 0.9.5. Resetting the settings from the settings dialog uses the new defaults.

**Closed by mikaeljorhult** 2017-09-06 17:58 UTC
