### ISSUE TITLE
[Feature request] Checkbox in the GUI

### ISSUE THREAD

**Issue by mrleblanc101** [mikaeljorhult/brackets-todo#131] opened 2017-01-11 10:43 UTC
Hi,
It would be nice to have a checkbox in the GUI itself to mark task as done. Clicking it would mark the task as done in the GUI and prepend the text in the comment with a [DONE] or [X] without removing the comment (removing the comment could be an option in the setting). This would be a HUGE improvement because it's long to type "[x]" in from of every task every time I complete them.

**Comment by mikaeljorhult** [comment] 2017-03-30 19:54
This is a duplicate of issue #7.

**Closed by mikaeljorhult** 2017-03-30 19:54 UTC
Labels: duplicate
