### ISSUE TITLE
Problem with //

### ISSUE THREAD

**Issue by malesa** [mikaeljorhult/brackets-todo#139] opened 2017-05-27 11:06 UTC
I don't know why comments // don't work.
I have fresh plugin installation. Trying to put some todos in my JS file (.js extension) I've found that:
/* TODO: It works */
// TODO: It doesn't work

**Comment by danielscake** [comment] 2017-05-28 19:47
None of my TODO's work. I tried both versions above.

**Comment by DavidCao22** [comment] 2017-05-30 22:45
I updated to the v0.9.3 and also had TODO's break. I had to roll back to v0.8.2 to get //TODO to work.

**Comment by malesa** [comment] 2017-05-31 06:37
I've figured out something - there is a problem with a closing expression. It works if you put any closing signs, eg:
// TODO: It also works */
So I've added a dot sign to the closing regular expression in the configuration and...
// TODO: Now it works too.
It seems that closing comments with line endind doesn't work. Maybe only on Windows?

**Comment by zishanj** [comment] 2017-05-31 07:39
with the latest version, it seems that the list does not refreshes well when switching between files. If add //TODO: and then save file, it will show in the list. If I move to another file and then goes back to older file with TODO then it shows blank list.

**Comment by patorpey** [comment] 2017-05-31 19:39
I've experienced something along these lines as well at least since v0.9.2. In my projects, only about one or two files are actually displaying TODOs and occasionally editing a TODO comment in one of the working files produced the behaviour @zishanj described.

Based on @malesa and @zishanj comments, I've found that it does seem like it has to do with Windows line terminations on files. Changing the suffix RegExp to
`):? *(.*?) ?(?=\*/|\r\n|\n|$)`
does seem to have helped.

**Comment by malesa** [comment] 2017-06-01 04:55
Thanks. It works now.

**Comment by mikaeljorhult** [comment] 2017-06-01 08:01
Great! Thank you for helping out @patorpey!

Would you mind submitting a pull request with the changes?

**Comment by zishanj** [comment] 2017-06-01 09:33
That suggested regex still does not work on my Mac. The `\n` linefeed character should work  on Mac because I have decoded the text and it shows that its using `LF ASCII 10` which is probably `\n`. Seems like the problem is somewhere else otherwise the default regex provided by Brackets would never work in first place, which I mentioned before.

**Comment by zishanj** [comment] 2017-06-01 09:38
Just an update... I have checked the default regex provided by Brackets on http://www.regex101.com and its working fine there. Seems like there is some issue with refreshing the TODO list dialog.

**Comment by mikaeljorhult** [comment] 2017-06-19 19:53
A fix for LF characters have been committed to  master. This will hopefully solve the problems you guys are having. Could you test this on your setups?

**Comment by zishanj** [comment] 2017-06-24 06:54
It does not work if I switch between files, otherwise it works well. 

PS: I am using Mac.

**Comment by alvint** [comment] 2017-07-13 15:19
The commit for this has caused issue #142. Please see there for details.

**Comment by mikaeljorhult** [comment] 2017-09-06 17:58
A fix for this is in the just released version 0.9.5. Resetting the settings from the settings dialog uses the new defaults.

**Closed by mikaeljorhult** 2017-09-06 17:58 UTC
